version: 2.1
jobs:
  build:
    working_directory: ~/cicd-pipeline
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@latest"
      - run:
          name: Install dependencies
          command: "npm install"
      - run:
          name: Test
          command: "npm test"
