version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
        name: "Install modules"
        command: npm install
      - run:
        name: "Start server"
        command: npm start
